modLoader = "javafml"
loaderVersion = "[3,)"
license = "Apache-2.0"

[[mods]]
modId = "neonetwork"
version = "${version}"
displayName = "NeoNetwork"
displayURL = "https://github.com/ThinkingStudios/NeoNetwork"
credits = "FabricMC, Sinytra"
authors = "TexTrue, ThinkingStudio"
description = '''
ForgifiedFabricAPI‘s networking api fork.
Low-level, vanilla protocol oriented networking hooks.
'''
logoFile = "icon.png"

[[accessTransformers]]
file="accesstransformer.cfg"

[[mixin]]
config = "fabric-networking-api-v1.mixins.json"

[[mixin]]
config = "fabric-networking-api-v1.client.mixins.json"

[[dependencies.neonetwork]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,]"
ordering = "NONE"
side = "BOTH"

[[dependencies.neonetwork]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,]"
ordering = "NONE"
side = "BOTH"
